from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf_report(report_data, output_path):

    pdf = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "Intelligent Data Quality Monitoring Report",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 20))

    dataset = report_data["datasetsummary"]
    quality = report_data["quality_report"]

    content.append(
        Paragraph(
            f"Dataset Name: {dataset['file_name']}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Total Records: {dataset['total_records']}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Total Columns: {dataset['total_column']}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Quality Report",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            f"Quality Score: {quality['QualityScore']}",
            styles["Normal"]
        )
    )

    content.append(
        Paragraph(
            f"Quality Status: {quality['QualityStatus']}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by Intelligent Data Quality Monitoring Platform",
            styles["Italic"]
        )
    )

    pdf.build(content)

    return output_path